<a href="https://colab.research.google.com/github/David-Arciniegas/Tarea-10-MN/blob/main/Tarea_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)  # Matriz identidad de tamaño n
    U = np.zeros((n, n))

    for j in range(n):
        # Calcular elementos de U
        for i in range(j+1):
            U[i][j] = A[i][j] - sum(L[i][k] * U[k][j] for k in range(i))

        # Calcular elementos de L
        for i in range(j, n):
            if U[j][j] == 0:
                raise ZeroDivisionError("Element in U is zero, cannot continue with LU decomposition.")
            L[i][j] = (A[i][j] - sum(L[i][k] * U[k][j] for k in range(j))) / U[j][j]

    return L, U

# Matrices del ejercicio
matrices = {
    'a': np.array([[2, -1, 1], [3, 3, 9], [3, 3, 5]]),
    'b': np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]]),
    'c': np.array([[2, 0, 0, 0], [1, 1.5, 0, 0], [0, -3, 0.5, 0], [2, -2, 1, 1]]),
    'd': np.array([[2.1756, 4.0231, -2.1732, 5.1967], [-4.0231, 6.0000, 0, 1.1973], [-1.0000, -5.2107, 1.1111, 0], [6.0235, 7.0000, 0, -4.1561]])
}

# Aplicando la descomposición LU a cada matriz
for key, matrix in matrices.items():
    L, U = lu_decomposition(matrix)
    print(f"Matriz {key}:")
    print("L =")
    print(L)
    print("U =")
    print(U)
    print("\n")


Matriz a:
L =
[[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]
U =
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]


Matriz b:
L =
[[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  1.19775553  1.        ]]
U =
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]


Matriz c:
L =
[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.         -2.          1.          0.        ]
 [ 1.         -1.33333333  2.          1.        ]]
U =
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]


Matriz d:
L =
[[ 1.          0.          0.          0.        ]
 [-1.84919103  1.          0.          0.        ]
 [-0.45964332 -0.25012194  1.          0.        ]
 [ 2.76866152 -0.30794361 -5.35228302  1.        ]]
U =
[[ 2.1756      4.0231     -2.1732      5.1967    ]
 [ 0.         13.43948042 -4.01866194 10.806991

In [2]:
import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)
    U = np.zeros((n, n))

    for j in range(n):
        for i in range(j+1):
            U[i][j] = A[i][j] - sum(L[i][k] * U[k][j] for k in range(i))
        for i in range(j, n):
            if U[j][j] == 0:
                raise ZeroDivisionError("Element in U is zero, cannot continue with LU decomposition.")
            L[i][j] = (A[i][j] - sum(L[i][k] * U[k][j] for k in range(j))) / U[j][j]

    return L, U

def forward_substitution(L, b):
    n = len(b)
    y = np.zeros(n)
    for i in range(n):
        y[i] = b[i] - sum(L[i][j] * y[j] for j in range(i))
    return y

def backward_substitution(U, y):
    n = len(y)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - sum(U[i][j] * x[j] for j in range(i+1, n))) / U[i][i]
    return x

def solve_lu(A, b):
    L, U = lu_decomposition(A)
    y = forward_substitution(L, b)
    x = backward_substitution(U, y)
    return x

# Definición de los sistemas de ecuaciones
sistemas = {
    'a': (np.array([[2, -1, 1], [3, 3, 9], [3, 3, 5]]), np.array([-1, 0, 4])),
    'b': (np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]]), np.array([1.984, -5.049, -3.895])),
    'c': (np.array([[2, 0, 0, 0], [1, 1.5, 0, 0], [0, -3, 0.5, 0], [2, -2, 1, 1]]), np.array([3, 4.5, -6.6, 0.8])),
    'd': (np.array([[2.1756, 4.0231, -2.1732, 5.1967], [-4.0231, 6.0000, 0, 1.1973], [-1.0000, -5.2107, 1.1111, 0], [6.0235, 7.0000, 0, -4.1561]]), np.array([17.102, -6.1593, 3.0004, 0]))
}

# Resolviendo cada sistema de ecuaciones
for key, (A, b) in sistemas.items():
    x = solve_lu(A, b)
    print(f"Solución para el sistema {key}: {x}")


Solución para el sistema a: [ 1.  2. -1.]
Solución para el sistema b: [1. 1. 1.]
Solución para el sistema c: [ 1.5  2.  -1.2  3. ]
Solución para el sistema d: [2.9398512  0.0706777  5.67773512 4.37981223]
